//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crash.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crash.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Animation ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnimationEntryController_Text {
            get {
                return ResourceManager.GetString("AnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkController_AcDelete {
            get {
                return ResourceManager.GetString("ChunkController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Chunk &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkController_AcDeleteWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeleteWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deprocess Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkController_AcDeprocess {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deprocess Chunk &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChunkController_AcDeprocessWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocessWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colored Animation ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColoredAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("ColoredAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No options available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Controller_NoOptionsAvailable {
            get {
                return ResourceManager.GetString("Controller_NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demo ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DemoEntryController_Text {
            get {
                return ResourceManager.GetString("DemoEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntityController_Text {
            get {
                return ResourceManager.GetString("EntityController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryChunkController_AcAddNew {
            get {
                return ResourceManager.GetString("EntryChunkController_AcAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryChunkController_AcImport {
            get {
                return ResourceManager.GetString("EntryChunkController_AcImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Entry &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryController_AcDelete {
            get {
                return ResourceManager.GetString("EntryController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deprocess Entry &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryController_AcDeprocess {
            get {
                return ResourceManager.GetString("EntryController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Entry &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryController_AcExport {
            get {
                return ResourceManager.GetString("EntryController_AcExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Entry &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EntryController_AcRename {
            get {
                return ResourceManager.GetString("EntryController_AcRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FrameController_Text {
            get {
                return ResourceManager.GetString("FrameController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a game version from the list below.
        ///NTSC-U, NTSC-J, and PAL are all supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameVersionForm_Message {
            get {
                return ResourceManager.GetString("GameVersionForm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prerelease Versions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameVersionForm_Prerelease {
            get {
                return ResourceManager.GetString("GameVersionForm_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release Versions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameVersionForm_Release {
            get {
                return ResourceManager.GetString("GameVersionForm_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Version Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameVersionForm_Text {
            get {
                return ResourceManager.GetString("GameVersionForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prototype GOOL ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GOOLv0EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv0EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOOL ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GOOLv1EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv1EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOOLv2 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GOOLv2EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv2EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOOLv3 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GOOLv3EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv3EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageEntryController_Text {
            get {
                return ResourceManager.GetString("ImageEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemController_Text {
            get {
                return ResourceManager.GetString("ItemController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MapEntryController_Text {
            get {
                return ResourceManager.GetString("MapEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed Model ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelEntryController_Compressed_Text {
            get {
                return ResourceManager.GetString("ModelEntryController_Compressed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelEntryController_Text {
            get {
                return ResourceManager.GetString("ModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MusicEntryController_Text {
            get {
                return ResourceManager.GetString("MusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalChunkController_Text {
            get {
                return ResourceManager.GetString("NormalChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcAddNormalChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddNormalChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Old Sound Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcAddOldSoundChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddOldSoundChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Sound Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcAddSoundChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddSoundChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Speech Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcAddSpeechChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddSpeechChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Wavebank Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcAddWavebankChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddWavebankChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Box Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcFixBoxCount {
            get {
                return ResourceManager.GetString("NSFController_AcFixBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Nitro Detonators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcFixDetonator {
            get {
                return ResourceManager.GetString("NSFController_AcFixDetonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcImportChunk {
            get {
                return ResourceManager.GetString("NSFController_AcImportChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show All Level Scenery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_AcShowLevel {
            get {
                return ResourceManager.GetString("NSFController_AcShowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSF File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NSFController_Text {
            get {
                return ResourceManager.GetString("NSFController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Animation ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("OldAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldCameraController_Text {
            get {
                return ResourceManager.GetString("OldCameraController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity {0} ({1}-{2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldEntityController_Text {
            get {
                return ResourceManager.GetString("OldEntityController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Model ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldModelEntryController_Text {
            get {
                return ResourceManager.GetString("OldModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Music ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldMusicEntryController_Text {
            get {
                return ResourceManager.GetString("OldMusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Scenery ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldSceneryEntryController_Text {
            get {
                return ResourceManager.GetString("OldSceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Sort List ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldSLSTEntryController_Text {
            get {
                return ResourceManager.GetString("OldSLSTEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Sound Chunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldSoundChunkController_Text {
            get {
                return ResourceManager.GetString("OldSoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Zone ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OldZoneEntryController_Text {
            get {
                return ResourceManager.GetString("OldZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Palette ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaletteEntryController_Text {
            get {
                return ResourceManager.GetString("PaletteEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prototype Animation ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProtoAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prototype Scenery ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProtoSceneryEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoSceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proto Zone ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProtoZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenery ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SceneryEntryController_Text {
            get {
                return ResourceManager.GetString("SceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort List ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SLSTEntryController_Text {
            get {
                return ResourceManager.GetString("SLSTEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound Chunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoundChunkController_Text {
            get {
                return ResourceManager.GetString("SoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoundEntryController_Text {
            get {
                return ResourceManager.GetString("SoundEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech Chunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechChunkController_Text {
            get {
                return ResourceManager.GetString("SpeechChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeechEntryController_Text {
            get {
                return ResourceManager.GetString("SpeechEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T11 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T11EntryController_Text {
            get {
                return ResourceManager.GetString("T11EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T15 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T15EntryController_Text {
            get {
                return ResourceManager.GetString("T15EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T17 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T17EntryController_Text {
            get {
                return ResourceManager.GetString("T17EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T1 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T1EntryController_Text {
            get {
                return ResourceManager.GetString("T1EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T21 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T21EntryController_Text {
            get {
                return ResourceManager.GetString("T21EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T6 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string T6EntryController_Text {
            get {
                return ResourceManager.GetString("T6EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextureChunkController_AcOpenViewer {
            get {
                return ResourceManager.GetString("TextureChunkController_AcOpenViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recalculate Checksum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextureChunkController_AcRecalcChecksum {
            get {
                return ResourceManager.GetString("TextureChunkController_AcRecalcChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextureChunkController_AcRename {
            get {
                return ResourceManager.GetString("TextureChunkController_AcRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture Chunk {1} ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextureChunkController_Text {
            get {
                return ResourceManager.GetString("TextureChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Chunk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnprocessedChunkController_AcProcess {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_AcProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unprocessed Chunk {1} (T{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnprocessedChunkController_Text {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Entry &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnprocessedEntryController_AcProcess {
            get {
                return ResourceManager.GetString("UnprocessedEntryController_AcProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unprocessed T{0} ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnprocessedEntryController_Text {
            get {
                return ResourceManager.GetString("UnprocessedEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wavebank Chunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WavebankChunkController_Text {
            get {
                return ResourceManager.GetString("WavebankChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wavebank ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WavebankEntryController_Text {
            get {
                return ResourceManager.GetString("WavebankEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Entity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoneEntryController_AcAddEntity {
            get {
                return ResourceManager.GetString("ZoneEntryController_AcAddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ZoneEntryController_Text", resourceCulture);
            }
        }
    }
}
