//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashEdit.CE.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrashEdit.CE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Close_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Close_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to close the NSF file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseNSF {
            get {
                return ResourceManager.GetString("CloseNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkAnimGrid {
            get {
                return ResourceManager.GetString("Config_chkAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Mica に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkApplyMica {
            get {
                return ResourceManager.GetString("Config_chkApplyMica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show collision boxes by default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkCollisionDisplay {
            get {
                return ResourceManager.GetString("Config_chkCollisionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete non-existent entries from load lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkDeleteInvalidEntries {
            get {
                return ResourceManager.GetString("Config_chkDeleteInvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Crash 2 time trial editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkEnableC2TT {
            get {
                return ResourceManager.GetString("Config_chkEnableC2TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable custom crates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkEnableCustomCrates {
            get {
                return ResourceManager.GetString("Config_chkEnableCustomCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable legacy entity editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkEnableLegacyEntityBox {
            get {
                return ResourceManager.GetString("Config_chkEnableLegacyEntityBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable 3D entity display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkEnableVisual {
            get {
                return ResourceManager.GetString("Config_chkEnableVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show debug console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkFont2DEnable {
            get {
                return ResourceManager.GetString("Config_chkFont2DEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show entity names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkFont3DEnable {
            get {
                return ResourceManager.GetString("Config_chkFont3DEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore errors when processing duplicated entries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkIgnoreDuplicatedEntryError {
            get {
                return ResourceManager.GetString("Config_chkIgnoreDuplicatedEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use legacy NSD patching from CrashEdit v0.2.49.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkLegacyPatchNSD {
            get {
                return ResourceManager.GetString("Config_chkLegacyPatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show collision node types as literal values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkLiteralCollisionTypes {
            get {
                return ResourceManager.GetString("Config_chkLiteralCollisionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Crash 1) Show normals in animations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkNormalDisplay {
            get {
                return ResourceManager.GetString("Config_chkNormalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output CLUT information to the console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkOutputCLUTInfo {
            get {
                return ResourceManager.GetString("Config_chkOutputCLUTInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output copying texture result to the console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkOutputCopyTextureResult {
            get {
                return ResourceManager.GetString("Config_chkOutputCopyTextureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output texture information to the console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkOutputModelTextureInfo {
            get {
                return ResourceManager.GetString("Config_chkOutputModelTextureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Crash 2) Patch GOOL frame groups imported from Crash 3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkPatchGOOLC3toC2 {
            get {
                return ResourceManager.GetString("Config_chkPatchGOOLC3toC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save NSF after NSD patching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkPatchNSDSavesNSF {
            get {
                return ResourceManager.GetString("Config_chkPatchNSDSavesNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show entity parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkShowEntityParams {
            get {
                return ResourceManager.GetString("Config_chkShowEntityParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show rendering errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkShowRenderingErrors {
            get {
                return ResourceManager.GetString("Config_chkShowRenderingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split animation viewer panels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkSplitViewerPanels {
            get {
                return ResourceManager.GetString("Config_chkSplitViewerPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show camera entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkViewCamera {
            get {
                return ResourceManager.GetString("Config_chkViewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show camera entity angles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkViewCameraAngle {
            get {
                return ResourceManager.GetString("Config_chkViewCameraAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show help text by default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkViewerShowHelp {
            get {
                return ResourceManager.GetString("Config_chkViewerShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show zone boundaries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkViewZoneBox {
            get {
                return ResourceManager.GetString("Config_chkViewZoneBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show zone names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkViewZoneName {
            get {
                return ResourceManager.GetString("Config_chkViewZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_cmdReset {
            get {
                return ResourceManager.GetString("Config_cmdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraAnimGrid {
            get {
                return ResourceManager.GetString("Config_fraAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraClearCol {
            get {
                return ResourceManager.GetString("Config_fraClearCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3D Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraFont {
            get {
                return ResourceManager.GetString("Config_fraFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraMisc {
            get {
                return ResourceManager.GetString("Config_fraMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collision Node Contrast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraNodeShadeAmt {
            get {
                return ResourceManager.GetString("Config_fraNodeShadeAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Window Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraSize {
            get {
                return ResourceManager.GetString("Config_fraSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblAnimGrid {
            get {
                return ResourceManager.GetString("Config_lblAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblFontName {
            get {
                return ResourceManager.GetString("Config_lblFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblFontSize {
            get {
                return ResourceManager.GetString("Config_lblFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblLang {
            get {
                return ResourceManager.GetString("Config_lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra feature: VB size is invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertVAB_Error {
            get {
                return ResourceManager.GetString("ConvertVAB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra feature: VB size does not match size specified in VH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertVHVB_Error {
            get {
                return ResourceManager.GetString("ConvertVHVB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type in a Model (or Compressed Model) name and press Enter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Crash3AnimationSelector_Desc {
            get {
                return ResourceManager.GetString("Crash3AnimationSelector_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Delete_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled (Bonus) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkBonusBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_ChkBonusBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkEnabled {
            get {
                return ResourceManager.GetString("EntityBox_ChkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkHex {
            get {
                return ResourceManager.GetString("EntityBox_ChkHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkSyncEntities {
            get {
                return ResourceManager.GetString("EntityBox_ChkSyncEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkSyncPositions {
            get {
                return ResourceManager.GetString("EntityBox_ChkSyncPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdAdd {
            get {
                return ResourceManager.GetString("EntityBox_CmdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Append に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdAppend {
            get {
                return ResourceManager.GetString("EntityBox_CmdAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdClearAllVictims {
            get {
                return ResourceManager.GetString("EntityBox_cmdClearAllVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdEditPath {
            get {
                return ResourceManager.GetString("EntityBox_CmdEditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdInsert {
            get {
                return ResourceManager.GetString("EntityBox_CmdInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interpolate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdInterpolate {
            get {
                return ResourceManager.GetString("EntityBox_CmdInterpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify List Integrity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdLoadListVerify {
            get {
                return ResourceManager.GetString("EntityBox_cmdLoadListVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdNext {
            get {
                return ResourceManager.GetString("EntityBox_CmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Payload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdPayload {
            get {
                return ResourceManager.GetString("EntityBox_cmdPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdPrevious {
            get {
                return ResourceManager.GetString("EntityBox_CmdPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdRemove {
            get {
                return ResourceManager.GetString("EntityBox_CmdRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdSyncEntities {
            get {
                return ResourceManager.GetString("EntityBox_CmdSyncEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraAvgDist {
            get {
                return ResourceManager.GetString("EntityBox_fraAvgDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_FraBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraCameraIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera SubIndex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraCameraSubIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraSubIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDA Section に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraDDASection {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDA Death Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraDDASettings {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw List A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraDrawListA {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw List B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraDrawListB {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEIDA {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEIDB {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEntityA {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEntityB {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field-of-View Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraFOV {
            get {
                return ResourceManager.GetString("EntityBox_fraFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field-of-View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraFOVFrame {
            get {
                return ResourceManager.GetString("EntityBox_fraFOVFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID &amp; Look-up ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraID {
            get {
                return ResourceManager.GetString("EntityBox_FraID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load List A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListA {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load List B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListB {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Load Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListPayload {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraMode {
            get {
                return ResourceManager.GetString("EntityBox_FraMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraName {
            get {
                return ResourceManager.GetString("EntityBox_FraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neighbors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraNeighbor {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neighbor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraNeighborSetting {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighborSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraOtherSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraPosition {
            get {
                return ResourceManager.GetString("EntityBox_FraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Modifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraScaling {
            get {
                return ResourceManager.GetString("EntityBox_FraScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraSLST {
            get {
                return ResourceManager.GetString("EntityBox_FraSLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Trial Reward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraTTReward {
            get {
                return ResourceManager.GetString("EntityBox_FraTTReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &amp; Subtype に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraType {
            get {
                return ResourceManager.GetString("EntityBox_FraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Draw Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraVerifyDrawList {
            get {
                return ResourceManager.GetString("EntityBox_fraVerifyDrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Victims に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraVictims {
            get {
                return ResourceManager.GetString("EntityBox_FraVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depth Modifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraZMod {
            get {
                return ResourceManager.GetString("EntityBox_FraZMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   as Number: {0:F3}
        ///as Angle: {1:F}deg
        ///as Time: {2:F}s
        ///as Meters: {3:F3}m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblArgAs {
            get {
                return ResourceManager.GetString("EntityBox_lblArgAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblFOVPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblFOVPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cam. Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborCamera {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborFlag {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborLink {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborZone {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblPayloadPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblPayloadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabCamera {
            get {
                return ResourceManager.GetString("EntityBox_TabCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabDrawList {
            get {
                return ResourceManager.GetString("EntityBox_TabDrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabGeneral {
            get {
                return ResourceManager.GetString("EntityBox_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabLoadList {
            get {
                return ResourceManager.GetString("EntityBox_TabLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabSpecial {
            get {
                return ResourceManager.GetString("EntityBox_TabSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Ctrl+C] Copy value of selected item
        ///[Ctrl+V] Paste copied value to selected item
        ///[Double-click / F2] Rename selected item
        ///[Ctrl+Shift+C] Copy entire list
        ///[Ctrl+Shift+X] Cut entire list
        ///[Ctrl+Shift+V] Paste copied list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_tipLists {
            get {
                return ResourceManager.GetString("EntityBox_tipLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Ctrl+C] Save selected fields
        ///[Delete] Remove selected fields に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityPropertyBox_tipProperties {
            get {
                return ResourceManager.GetString("EntityPropertyBox_tipProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Ctrl+V] Copy fields in selected item
        ///[Double-click / F2] Rename selected item
        ///[Delete] Remove selected items
        ///--------------------------------
        ///[Ctrl+R] Reload list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityPropertyBox_tipSavedProperties {
            get {
                return ResourceManager.GetString("EntityPropertyBox_tipSavedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Abort {
            get {
                return ResourceManager.GetString("ErrorReporter_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Break out to a debugger. (Experts only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Break {
            get {
                return ResourceManager.GetString("ErrorReporter_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore the error and continue anyway. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Ignore {
            get {
                return ResourceManager.GetString("ErrorReporter_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore the error and all others for this object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_IgnoreAll {
            get {
                return ResourceManager.GetString("ErrorReporter_IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip this object, leaving it unprocessed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Skip {
            get {
                return ResourceManager.GetString("ErrorReporter_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Title {
            get {
                return ResourceManager.GetString("ErrorReporter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Spawn Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GenerateSpawnPoint_Title {
            get {
                return ResourceManager.GetString("GenerateSpawnPoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GOOLBox_Goto {
            get {
                return ResourceManager.GetString("GOOLBox_Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [N] Input the EID for &quot;NONE!&quot;
        ///[Space] Clear selected cell
        ///[Ctrl + Space] Clear selected chunk
        ///[Z] Toggle chunk name view mode
        ///[Ctrl + G] Goto
        ///[+ / - ] Change line width
        ///
        ///[Mouse drag] Select multiple cells
        ///[Ctrl + C] Copy selected words as bytes
        ///[Ctrl + X] Cut selected words as bytes
        ///[Ctrl + V] Paste to words as bytes
        ///[Ctrl + Shift + C] Copy selected words as EID
        ///[Ctrl + Shift + X] Cut selected words as EID
        ///[Ctrl + Shift + V] Paste to words as EID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HexView_tip {
            get {
                return ResourceManager.GetString("HexView_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputWindow_cmdCancel {
            get {
                return ResourceManager.GetString("InputWindow_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm {
            get {
                return ResourceManager.GetString("InterpolatorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdCancel {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdFirst {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdLast {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdNext {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdOK {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdPrev {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraAmount {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start/End Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraBound {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress Function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraFunction {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraOrder {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Positions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraPosition {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraTension {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English (Default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUE file already exists, will not be modified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueExists {
            get {
                return ResourceManager.GetString("MakeBIN_CueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create CUE file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueFail {
            get {
                return ResourceManager.GetString("MakeBIN_CueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created matching CUE file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueSuccess {
            get {
                return ResourceManager.GetString("MakeBIN_CueSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DRNSF returned an error. No region has been applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Error {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to launch DRNSF. Reason: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Fail {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launching DRNSF to apply selected region... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Launch {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Region applied successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Success {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find DRNSF exe. Please place this in the same directory as CrashEdit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Unavailable {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Making BIN... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_Making {
            get {
                return ResourceManager.GetString("MakeBIN_Making", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created BIN file without region OK. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_NoRegOK {
            get {
                return ResourceManager.GetString("MakeBIN_NoRegOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected drive or folder does not contain SYSTEM.CNF or PSX.EXE. At least one of these is required for a bootable PSX CD image. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_NoSystemFiles {
            get {
                return ResourceManager.GetString("MakeBIN_NoSystemFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_Title {
            get {
                return ResourceManager.GetString("MakeBIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_PatchNSD {
            get {
                return ResourceManager.GetString("Menu_File_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_EntryID {
            get {
                return ResourceManager.GetString("Menu_Find_EntryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_EntryName {
            get {
                return ResourceManager.GetString("Menu_Find_EntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_Find {
            get {
                return ResourceManager.GetString("Menu_Find_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_FindNext {
            get {
                return ResourceManager.GetString("Menu_Find_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_ObjectName {
            get {
                return ResourceManager.GetString("Menu_Find_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_CurrentState {
            get {
                return ResourceManager.GetString("Menu_Undo_CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_RedoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_RedoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_UndoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_UndoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm {
            get {
                return ResourceManager.GetString("NewEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm_fraName {
            get {
                return ResourceManager.GetString("NewEntryForm_fraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm_fraType {
            get {
                return ResourceManager.GetString("NewEntryForm_fraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Mouse drag] Move row
        ///[Right-click] Show context menu
        ///[Ctrl + C] Copy selected spawn point
        ///[Ctrl + V] Paste copied value to selected spawn point  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NSDBox_tipSpawnPoint {
            get {
                return ResourceManager.GetString("NSDBox_tipSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra Features に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbbExtra {
            get {
                return ResourceManager.GetString("OldMainForm_tbbExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert VAB to DLS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxConvertVAB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert VH+VB to DLS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxConvertVHVB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVHVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Converter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxEntryConverter {
            get {
                return ResourceManager.GetString("OldMainForm_tbxEntryConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate EID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxGenerateEID {
            get {
                return ResourceManager.GetString("OldMainForm_tbxGenerateEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Spawn Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxGenerateSpawnPoint {
            get {
                return ResourceManager.GetString("OldMainForm_tbxGenerateSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxMakeBIN {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VAB Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxVABTool {
            get {
                return ResourceManager.GetString("OldMainForm_tbxVABTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Error1 {
            get {
                return ResourceManager.GetString("PatchNSD_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSD patching is not supported for this game version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Error2 {
            get {
                return ResourceManager.GetString("PatchNSD_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSD file &apos;{0}&apos; does not exist! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Error3 {
            get {
                return ResourceManager.GetString("PatchNSD_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Title1 {
            get {
                return ResourceManager.GetString("PatchNSD_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loadlist autosorter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Title2 {
            get {
                return ResourceManager.GetString("PatchNSD_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite the NSD file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD1 {
            get {
                return ResourceManager.GetString("PatchNSD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to sort all loadlists according to the NSD? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD2 {
            get {
                return ResourceManager.GetString("PatchNSD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The chunk contents in this NSF may have been moved in accordance to the patched NSD and needs to be resaved. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD3 {
            get {
                return ResourceManager.GetString("PatchNSD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSF filename &apos;{0}&apos; is not appropriate! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error1 {
            get {
                return ResourceManager.GetString("Playtest_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error2 {
            get {
                return ResourceManager.GetString("Playtest_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSD file &apos;{0}&apos; does not exist! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error3 {
            get {
                return ResourceManager.GetString("Playtest_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find exe file (PSX.EXE, SCUS_123.45, SLES_123.45, etc). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error4 {
            get {
                return ResourceManager.GetString("Playtest_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find pcsx-hdbg exe. Please place this in the same directory as CrashEdit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error5 {
            get {
                return ResourceManager.GetString("Playtest_Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playtest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Title {
            get {
                return ResourceManager.GetString("Playtest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reset_onfirmationPrompt {
            get {
                return ResourceManager.GetString("Reset_onfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This requires a restart. Do you want to restart now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Restart_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Restart_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Save_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF {
            get {
                return ResourceManager.GetString("SaveNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A packing error occurred. The chunk containing entry &apos;{0}&apos; has over 64 KB of data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error1 {
            get {
                return ResourceManager.GetString("SaveNSF_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An IO error occurred.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error2 {
            get {
                return ResourceManager.GetString("SaveNSF_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unauthorized access error occurred.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error3 {
            get {
                return ResourceManager.GetString("SaveNSF_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Title {
            get {
                return ResourceManager.GetString("SaveNSF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting to COLLADA is experimental. Texture information will not be exported. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportCOLLADA {
            get {
                return ResourceManager.GetString("Scenery_ExportCOLLADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export as COLLADA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportCOLLADA_Title {
            get {
                return ResourceManager.GetString("Scenery_ExportCOLLADA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting to Wavefront OBJ (.obj) is experimental. Texture and color information will not be exported. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportOBJ {
            get {
                return ResourceManager.GetString("Scenery_ExportOBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export as OBJ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportOBJ_Title {
            get {
                return ResourceManager.GetString("Scenery_ExportOBJ_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting to Stanford PLY (.ply) is experimental. Texture information will not be exported. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportPLY {
            get {
                return ResourceManager.GetString("Scenery_ExportPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export as PLY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenery_ExportPLY_Title {
            get {
                return ResourceManager.GetString("Scenery_ExportPLY_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show GOOL Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowGOOLMap_Title {
            get {
                return ResourceManager.GetString("ShowGOOLMap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &quot;{0}&quot; has not been saved since it was last modified. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CloseDirtyFilePrompt {
            get {
                return ResourceManager.GetString("Text_CloseDirtyFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Click] Open viewer
        ///[Ctrl+R] Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureChunkBox_TipText {
            get {
                return ResourceManager.GetString("TextureChunkBox_TipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox1 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blend Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox2 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox4 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox5 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Right-click] Save selected texture region to file
        ///[Ctrl+C] Copy texture to buffer
        ///[Ctrl+X] Cut texture to buffer
        ///[Ctrl+V] Paste texture from buffer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_tipViewer {
            get {
                return ResourceManager.GetString("TextureViewer_tipViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_InputError {
            get {
                return ResourceManager.GetString("Title_InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture Replacement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_TextureReplacement {
            get {
                return ResourceManager.GetString("Title_TextureReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validation Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ValidationError {
            get {
                return ResourceManager.GetString("Title_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_BIN {
            get {
                return ResourceManager.GetString("Toolbar_BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Close {
            get {
                return ResourceManager.GetString("Toolbar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Find {
            get {
                return ResourceManager.GetString("Toolbar_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_FindNext {
            get {
                return ResourceManager.GetString("Toolbar_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goto EID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_GotoEID {
            get {
                return ResourceManager.GetString("Toolbar_GotoEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Open {
            get {
                return ResourceManager.GetString("Toolbar_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_PAL {
            get {
                return ResourceManager.GetString("Toolbar_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Patch {
            get {
                return ResourceManager.GetString("Toolbar_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_PatchNSD {
            get {
                return ResourceManager.GetString("Toolbar_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Play {
            get {
                return ResourceManager.GetString("Toolbar_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_RedoAction {
            get {
                return ResourceManager.GetString("Toolbar_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_RedoNone {
            get {
                return ResourceManager.GetString("Toolbar_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Save {
            get {
                return ResourceManager.GetString("Toolbar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_SaveAs {
            get {
                return ResourceManager.GetString("Toolbar_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_UndoAction {
            get {
                return ResourceManager.GetString("Toolbar_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Undock {
            get {
                return ResourceManager.GetString("Toolbar_Undock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_UndoNone {
            get {
                return ResourceManager.GetString("Toolbar_UndoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left mouse to aim に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_Aim {
            get {
                return ResourceManager.GetString("ViewerControls_Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left mouse to aim, scroll wheel to zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_AimAndZoom {
            get {
                return ResourceManager.GetString("ViewerControls_AimAndZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change culling modes (current: {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ChangeCullMode {
            get {
                return ResourceManager.GetString("ViewerControls_ChangeCullMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter camera rail view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_EnterZoneAnchor {
            get {
                return ResourceManager.GetString("ViewerControls_EnterZoneAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to normal view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ExitZoneAnchor {
            get {
                return ResourceManager.GetString("ViewerControls_ExitZoneAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold right-click to increase movement speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_FastMove {
            get {
                return ResourceManager.GetString("ViewerControls_FastMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W/A/S/D to move, Q/E to pan up/down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_Move {
            get {
                return ResourceManager.GetString("ViewerControls_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle aligned movement ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_MoveAligned {
            get {
                return ResourceManager.GetString("ViewerControls_MoveAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open octree node window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_OpenOctreeWindow {
            get {
                return ResourceManager.GetString("ViewerControls_OpenOctreeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left/Right to change model (current: {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_PickModel {
            get {
                return ResourceManager.GetString("ViewerControls_PickModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ResetCamera {
            get {
                return ResourceManager.GetString("ViewerControls_ResetCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle collision boxes ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleCollisionAnim {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleCollisionAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle 3D entity display ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleEntityVisual {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleEntityVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle help text ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleHelp {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle animation interpolation ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleLerp {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleLerp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle automatic model cycling ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleModelCycle {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleModelCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle normals ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleNormals {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleNormals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle half-speed animations ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleSlowAnim {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleSlowAnim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle textures ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleTextures {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle time trial mode ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleTimeTrial {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleTimeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle zone collision octree ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleZoneOctree {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleZoneOctree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip octree ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleZoneOctreeFlip {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleZoneOctreeFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle neighbor zone octree ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleZoneOctreeNeighbors {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleZoneOctreeNeighbors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle octree wireframe ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ToggleZoneOctreeOutline {
            get {
                return ResourceManager.GetString("ViewerControls_ToggleZoneOctreeOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle detach from rail ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorDetach {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W/A/S/D/Q/E to move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorMove {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to next camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorNextCam {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorNextCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse to pan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorPan {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to previous camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorPrevCam {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorPrevCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle sort list ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_ZoneAnchorSortList {
            get {
                return ResourceManager.GetString("ViewerControls_ZoneAnchorSortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll wheel to zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerControls_Zoom {
            get {
                return ResourceManager.GetString("ViewerControls_Zoom", resourceCulture);
            }
        }
    }
}
