//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrashEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Close_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Close_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to close the NSF file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseNSF {
            get {
                return ResourceManager.GetString("CloseNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_053 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_053", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_063 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_064 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_068 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkAnimGrid {
            get {
                return ResourceManager.GetString("Config_chkAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display frame collision by default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkCollisionDisplay {
            get {
                return ResourceManager.GetString("Config_chkCollisionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display custom crates (modded BoxsC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkCustomCrates {
            get {
                return ResourceManager.GetString("Config_chkCustomCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Patch NSD) Delete non-existent entries from load lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkDeleteInvalidEntries {
            get {
                return ResourceManager.GetString("Config_chkDeleteInvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display detailed collision type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkDetailedCollision {
            get {
                return ResourceManager.GetString("Config_chkDetailedCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display normals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkNormalDisplay {
            get {
                return ResourceManager.GetString("Config_chkNormalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Patch NSD) Use old NSD patching from CrashEdit v0.2.49.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkOldPatchNSD {
            get {
                return ResourceManager.GetString("Config_chkOldPatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Patch NSD) Always save NSF after NSD patching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkPatchNSDSavesNSF {
            get {
                return ResourceManager.GetString("Config_chkPatchNSDSavesNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Crash 3) Used saved animation-model links に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_chkUseAnimLinks {
            get {
                return ResourceManager.GetString("Config_chkUseAnimLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_cmdHelp {
            get {
                return ResourceManager.GetString("Config_cmdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_cmdReset {
            get {
                return ResourceManager.GetString("Config_cmdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reset the settings? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_cmdResetText {
            get {
                return ResourceManager.GetString("Config_cmdResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_cmdResetTitle {
            get {
                return ResourceManager.GetString("Config_cmdResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation Viewer World Grid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraAnimGrid {
            get {
                return ResourceManager.GetString("Config_fraAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraClearCol {
            get {
                return ResourceManager.GetString("Config_fraClearCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Key Binding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraKeyBinds {
            get {
                return ResourceManager.GetString("Config_fraKeyBinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language (requires restart) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_FraLang {
            get {
                return ResourceManager.GetString("Config_FraLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Window Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_fraSize {
            get {
                return ResourceManager.GetString("Config_fraSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblAnimGrid {
            get {
                return ResourceManager.GetString("Config_lblAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblH {
            get {
                return ResourceManager.GetString("Config_lblH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config_lblW {
            get {
                return ResourceManager.GetString("Config_lblW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra feature: VB size is invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertVAB_Error {
            get {
                return ResourceManager.GetString("ConvertVAB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extra feature: VB size does not match size specified in VH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertVHVB_Error {
            get {
                return ResourceManager.GetString("ConvertVHVB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type in a Model (or Compressed Model) name and press Enter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Crash3AnimationSelector_Desc {
            get {
                return ResourceManager.GetString("Crash3AnimationSelector_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled (Bonus) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkBonusBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_ChkBonusBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkEnabled {
            get {
                return ResourceManager.GetString("EntityBox_ChkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_ChkHex {
            get {
                return ResourceManager.GetString("EntityBox_ChkHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdAdd {
            get {
                return ResourceManager.GetString("EntityBox_CmdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Append に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdAppend {
            get {
                return ResourceManager.GetString("EntityBox_CmdAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdClearAllVictims {
            get {
                return ResourceManager.GetString("EntityBox_cmdClearAllVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdInsert {
            get {
                return ResourceManager.GetString("EntityBox_CmdInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interpolate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdInterpolate {
            get {
                return ResourceManager.GetString("EntityBox_CmdInterpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify List Integrity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdLoadListVerify {
            get {
                return ResourceManager.GetString("EntityBox_cmdLoadListVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdNext {
            get {
                return ResourceManager.GetString("EntityBox_CmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Payload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_cmdPayload {
            get {
                return ResourceManager.GetString("EntityBox_cmdPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdPrevious {
            get {
                return ResourceManager.GetString("EntityBox_CmdPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_CmdRemove {
            get {
                return ResourceManager.GetString("EntityBox_CmdRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraAvgDist {
            get {
                return ResourceManager.GetString("EntityBox_fraAvgDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_FraBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraCameraIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera SubIndex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraCameraSubIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraSubIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDA Section に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraDDASection {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDA Death Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraDDASettings {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw List A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraDrawListA {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw List B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraDrawListB {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEIDA {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEIDB {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEntityA {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraEntityB {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field-of-View Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraFOV {
            get {
                return ResourceManager.GetString("EntityBox_fraFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field-of-View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraFOVFrame {
            get {
                return ResourceManager.GetString("EntityBox_fraFOVFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraID {
            get {
                return ResourceManager.GetString("EntityBox_FraID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load List A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListA {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load List B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListB {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Load Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraLoadListPayload {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraMode {
            get {
                return ResourceManager.GetString("EntityBox_FraMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraName {
            get {
                return ResourceManager.GetString("EntityBox_FraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neighbors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraNeighbor {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neighbor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_fraNeighborSetting {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighborSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraOtherSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraPosition {
            get {
                return ResourceManager.GetString("EntityBox_FraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Modifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraScaling {
            get {
                return ResourceManager.GetString("EntityBox_FraScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraSLST {
            get {
                return ResourceManager.GetString("EntityBox_FraSLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtype に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraSubtype {
            get {
                return ResourceManager.GetString("EntityBox_FraSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Trial Reward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraTTReward {
            get {
                return ResourceManager.GetString("EntityBox_FraTTReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraType {
            get {
                return ResourceManager.GetString("EntityBox_FraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Victims に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraVictims {
            get {
                return ResourceManager.GetString("EntityBox_FraVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depth Modifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_FraZMod {
            get {
                return ResourceManager.GetString("EntityBox_FraZMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblFOVPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblFOVPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cam. Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborCamera {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborFlag {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborLink {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblNeighborZone {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_lblPayloadPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblPayloadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabCamera {
            get {
                return ResourceManager.GetString("EntityBox_TabCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabDrawList {
            get {
                return ResourceManager.GetString("EntityBox_TabDrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabGeneral {
            get {
                return ResourceManager.GetString("EntityBox_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabLoadList {
            get {
                return ResourceManager.GetString("EntityBox_TabLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntityBox_TabSpecial {
            get {
                return ResourceManager.GetString("EntityBox_TabSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Abort {
            get {
                return ResourceManager.GetString("ErrorReporter_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Break out to a debugger. (Experts only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Break {
            get {
                return ResourceManager.GetString("ErrorReporter_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore the error and continue anyway. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Ignore {
            get {
                return ResourceManager.GetString("ErrorReporter_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore the error and all others for this object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_IgnoreAll {
            get {
                return ResourceManager.GetString("ErrorReporter_IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip this object, leaving it unprocessed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Skip {
            get {
                return ResourceManager.GetString("ErrorReporter_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReporter_Title {
            get {
                return ResourceManager.GetString("ErrorReporter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputWindow_cmdCancel {
            get {
                return ResourceManager.GetString("InputWindow_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interpolate Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm {
            get {
                return ResourceManager.GetString("InterpolatorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdCancel {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdFirst {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdLast {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdNext {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdOK {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_cmdPrev {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraAmount {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start/End Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraBound {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress Function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraFunction {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraOrder {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Positions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraPosition {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterpolatorForm_fraTension {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English (Default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUE file already exists, will not be modified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueExists {
            get {
                return ResourceManager.GetString("MakeBIN_CueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create CUE file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueFail {
            get {
                return ResourceManager.GetString("MakeBIN_CueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created matching CUE file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_CueSuccess {
            get {
                return ResourceManager.GetString("MakeBIN_CueSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DRNSF returned an error. No region has been applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Error {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to launch DRNSF. Reason: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Fail {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launching DRNSF to apply selected region... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Launch {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Region applied successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Success {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find DRNSF exe. Please place this in the same directory as CrashEdit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_DRNSF_Unavailable {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Making BIN... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_Making {
            get {
                return ResourceManager.GetString("MakeBIN_Making", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created BIN file without region OK. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_NoRegOK {
            get {
                return ResourceManager.GetString("MakeBIN_NoRegOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected drive or folder does not contain SYSTEM.CNF or PSX.EXE. At least one of these is required for a bootable PSX CD image. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_NoSystemFiles {
            get {
                return ResourceManager.GetString("MakeBIN_NoSystemFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MakeBIN_Title {
            get {
                return ResourceManager.GetString("MakeBIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_PatchNSD {
            get {
                return ResourceManager.GetString("Menu_File_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_EntryID {
            get {
                return ResourceManager.GetString("Menu_Find_EntryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_EntryName {
            get {
                return ResourceManager.GetString("Menu_Find_EntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_Find {
            get {
                return ResourceManager.GetString("Menu_Find_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_FindNext {
            get {
                return ResourceManager.GetString("Menu_Find_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Find_ObjectName {
            get {
                return ResourceManager.GetString("Menu_Find_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_CurrentState {
            get {
                return ResourceManager.GetString("Menu_Undo_CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_RedoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_RedoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_UndoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Undo_UndoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm {
            get {
                return ResourceManager.GetString("NewEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm_fraName {
            get {
                return ResourceManager.GetString("NewEntryForm_fraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewEntryForm_fraType {
            get {
                return ResourceManager.GetString("NewEntryForm_fraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_006 {
            get {
                object obj = ResourceManager.GetObject("objects_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_006_red {
            get {
                object obj = ResourceManager.GetObject("objects_006_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_006_yellow {
            get {
                object obj = ResourceManager.GetObject("objects_006_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012 {
            get {
                object obj = ResourceManager.GetObject("objects_012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_blue {
            get {
                object obj = ResourceManager.GetObject("objects_012_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_code {
            get {
                object obj = ResourceManager.GetObject("objects_012_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_crimson {
            get {
                object obj = ResourceManager.GetObject("objects_012_crimson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_gray {
            get {
                object obj = ResourceManager.GetObject("objects_012_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_lime {
            get {
                object obj = ResourceManager.GetObject("objects_012_lime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_violet {
            get {
                object obj = ResourceManager.GetObject("objects_012_violet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_020 {
            get {
                object obj = ResourceManager.GetObject("objects_020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_028 {
            get {
                object obj = ResourceManager.GetObject("objects_028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_029 {
            get {
                object obj = ResourceManager.GetObject("objects_029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_036 {
            get {
                object obj = ResourceManager.GetObject("objects_036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_037 {
            get {
                object obj = ResourceManager.GetObject("objects_037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_053_blue {
            get {
                object obj = ResourceManager.GetObject("objects_053_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_053_white {
            get {
                object obj = ResourceManager.GetObject("objects_053_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_070 {
            get {
                object obj = ResourceManager.GetObject("objects_070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap objects_079 {
            get {
                object obj = ResourceManager.GetObject("objects_079", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Extra Features に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbbExtra {
            get {
                return ResourceManager.GetString("OldMainForm_tbbExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert VAB to DLS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxConvertVAB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert VH+VB to DLS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxConvertVHVB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVHVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN (no region) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxMakeBIN {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN (PAL) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxMakeBINEUR {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN (NTSC-J) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxMakeBINJAP {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINJAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make BIN (NTSC-U/C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OldMainForm_tbxMakeBINUSA {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Error1 {
            get {
                return ResourceManager.GetString("PatchNSD_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSD patching is not supported for this game version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Error2 {
            get {
                return ResourceManager.GetString("PatchNSD_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Title1 {
            get {
                return ResourceManager.GetString("PatchNSD_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loadlist autosorter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD_Title2 {
            get {
                return ResourceManager.GetString("PatchNSD_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite the NSD file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD1 {
            get {
                return ResourceManager.GetString("PatchNSD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to sort all loadlists according to the NSD? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD2 {
            get {
                return ResourceManager.GetString("PatchNSD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The chunk contents in this NSF may have been moved in accordance to the patched NSD and needs to be resaved. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PatchNSD3 {
            get {
                return ResourceManager.GetString("PatchNSD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_014 {
            get {
                object obj = ResourceManager.GetObject("People_014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_017 {
            get {
                object obj = ResourceManager.GetObject("People_017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_020 {
            get {
                object obj = ResourceManager.GetObject("People_020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_020_code {
            get {
                object obj = ResourceManager.GetObject("People_020_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_020_cyan {
            get {
                object obj = ResourceManager.GetObject("People_020_cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap People_020_red {
            get {
                object obj = ResourceManager.GetObject("People_020_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   NSF filename &apos;{0}&apos; is not appropriate! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error1 {
            get {
                return ResourceManager.GetString("Playtest_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error2 {
            get {
                return ResourceManager.GetString("Playtest_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSD file &apos;{0}&apos; does not exist! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error3 {
            get {
                return ResourceManager.GetString("Playtest_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find exe file (PSX.EXE, SCUS_123.45, SLES_123.45, etc). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Error4 {
            get {
                return ResourceManager.GetString("Playtest_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playtest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playtest_Title {
            get {
                return ResourceManager.GetString("Playtest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Confirmation Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Save_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF {
            get {
                return ResourceManager.GetString("SaveNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A packing error occurred. The chunk containing entry &apos;{0}&apos; has over 64 KB of data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error1 {
            get {
                return ResourceManager.GetString("SaveNSF_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An IO error occurred.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error2 {
            get {
                return ResourceManager.GetString("SaveNSF_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unauthorized access error occurred.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Error3 {
            get {
                return ResourceManager.GetString("SaveNSF_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveNSF_Title {
            get {
                return ResourceManager.GetString("SaveNSF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &quot;{0}&quot; has not been saved since it was last modified. Continue anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CloseDirtyFilePrompt {
            get {
                return ResourceManager.GetString("Text_CloseDirtyFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox1 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blend Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox2 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox4 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextureViewer_groupBox5 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Close {
            get {
                return ResourceManager.GetString("Toolbar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Find {
            get {
                return ResourceManager.GetString("Toolbar_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_FindNext {
            get {
                return ResourceManager.GetString("Toolbar_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goto EID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_GotoEID {
            get {
                return ResourceManager.GetString("Toolbar_GotoEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Open {
            get {
                return ResourceManager.GetString("Toolbar_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch NSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_PatchNSD {
            get {
                return ResourceManager.GetString("Toolbar_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_RedoAction {
            get {
                return ResourceManager.GetString("Toolbar_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_RedoNone {
            get {
                return ResourceManager.GetString("Toolbar_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Save {
            get {
                return ResourceManager.GetString("Toolbar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_UndoAction {
            get {
                return ResourceManager.GetString("Toolbar_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_UndoNone {
            get {
                return ResourceManager.GetString("Toolbar_UndoNone", resourceCulture);
            }
        }
    }
}
